### ISSUE TITLE
Not working in Ubuntu Bash on Windows 

### ISSUE THREAD

**Issue by laggingreflex** [scravy/node-macaddress#8]
Using it on [Windows Subsystem for Linux](https://blogs.msdn.microsoft.com/wsl/2016/04/22/windows-subsystem-for-linux-overview/) gives this error:

```
> macaddress.one(function (err, mac) {console.log("Mac address for this host: %s", mac);});
Error: EINVAL: invalid argument, uv_interface_addresses
    at Error (native)
    at Object.lib.networkInterfaces (/mnt/c/.../node_modules/macaddress/index.js:31:21)
    at Object.lib.one (/mnt/c/.../node_modules/macaddress/index.js:79:26)
```

**Comment by laggingreflex** [comment]
It seems either Webpack or Babel (or one of their nested dependencies) depend on this as well, so they're failing too...

```
ERROR in ../~/css-loader!./app/.../handsontable-pro/dist/handsontable.full.css
Module build failed: Error: EINVAL: invalid argument, uv_interface_addresses
    at Error (native)
    at Object.lib.networkInterfaces (/mnt/c/...project/node_modules/macaddress/index.js:31:21)
    at Object.lib.one (/mnt/c/...project/node_modules/macaddress/index.js:79:26)
    at Object.<anonymous> (/mnt/c/...project/node_modules/uniqid/index.js:15:77)
    at Object.require.extensions.(anonymous function) [as .js] (/mnt/c/...project/node_modules/babel-register/lib/node.js:156:7)
    at Object.<anonymous> (/mnt/c/...project/node_modules/postcss-filter-plugins/dist/index.js:9:15)
    at Object.require.extensions.(anonymous function) [as .js] (/mnt/c/...project/node_modules/babel-register/lib/node.js:156:7)
    at Object.<anonymous> (/mnt/c/...project/node_modules/cssnano/dist/index.js:21:30)
    at Object.require.extensions.(anonymous function) [as .js] (/mnt/c/...project/node_modules/babel-register/lib/node.js:156:7)
 @ ../~/style-loader!../~/css-loader!./app/.../handsontable-pro/dist/handsontable.full.css 4:14-106 13:2-17:4 14:20-112

ERROR in ./app/.../styles.css
Module build failed: ModuleBuildError: Module build failed: Error: EINVAL: invalid argument, uv_interface_addresses
    at Object.lib.networkInterfaces (/mnt/c/...project/node_modules/macaddress/index.js:31:21)
    at Object.lib.one (/mnt/c/...project/node_modules/macaddress/index.js:79:26)
    at Object.<anonymous> (/mnt/c/...project/node_modules/uniqid/index.js:15:77)
    at Object.require.extensions.(anonymous function) [as .js] (/mnt/c/...project/node_modules/babel-register/lib/node.js:156:7)
    at Object.<anonymous> (/mnt/c/...project/node_modules/postcss-filter-plugins/dist/index.js:9:15)
    at Object.require.extensions.(anonymous function) [as .js] (/mnt/c/...project/node_modules/babel-register/lib/node.js:156:7)
    at Object.<anonymous> (/mnt/c/...project/node_modules/cssnano/dist/index.js:21:30)
    at Object.require.extensions.(anonymous function) [as .js] (/mnt/c/...project/node_modules/babel-register/lib/node.js:156:7)
    at /mnt/c/...project/node_modules/webpack/lib/NormalModule.js:137:35
    at /mnt/c/...project/node_modules/loader-runner/lib/LoaderRunner.js:328:11
```

**Comment by soluml** [comment]
+1 ran into this as well. Does not work on my ubuntu installation on Windows.

**Comment by soluml** [comment]
@laggingreflex this looks to be a Bash on Windows issue -> https://github.com/Microsoft/BashOnWindows/issues/468

**Comment by infeng** [comment]
i have the same proplem

**Comment by shengliangli** [comment]
i have the same proplem too

**Comment by ryanhugh** [comment]
I have the same problem. Just wanted to add that you can get the mac address inside Bash on Windows with this command.

`cat /sys/class/net/eth0/address`

 http://stackoverflow.com/questions/17950405/im-trying-to-get-the-mac-address-as-a-variable-in-linux-but-it-rarely-works
